
import { jsPDF } from 'jspdf'
import 'jspdf-autotable'
import * as XLSX from 'xlsx'
import { format } from 'date-fns'

declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF
  }
}

interface ExportConfig {
  title: string
  subtitle?: string
  organizationName: string
  columns: { header: string; dataKey: string }[]
  data: any[]
  summary?: Record<string, string | number>
  filters?: Record<string, any>
}

export class ReportExportService {
  /**
   * Generates and downloads a professional ERP-style PDF report
   */
  static async exportToPDF(config: ExportConfig) {
    const { title, subtitle, organizationName, columns, data, summary, filters } = config
    const doc = new jsPDF('p', 'mm', 'a4')
    const pageWidth = doc.internal.pageSize.width
    const timestamp = format(new Date(), 'PPP p')

    // --- Header Section ---
    doc.setFillColor(240, 240, 240)
    doc.rect(0, 0, pageWidth, 40, 'F')
    
    // Logo / Brand
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(22)
    doc.setTextColor(0, 0, 0)
    doc.text('ECRAFTZ', 15, 18)
    
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(100, 100, 100)
    doc.text(organizationName, 15, 25)
    doc.text(`Generated: ${timestamp}`, 15, 30)
    
    doc.setFontSize(8)
    doc.text('ERP SYSTEM REPORT | CONFIDENTIAL', pageWidth - 15, 18, { align: 'right' })

    // --- Report Title ---
    doc.setFontSize(18)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(0, 0, 0)
    doc.text(title.toUpperCase(), 15, 55)
    
    if (subtitle) {
      doc.setFontSize(11)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(100, 100, 100)
      doc.text(subtitle, 15, 62)
    }

    // --- Filters Applied ---
    if (filters && Object.keys(filters).length > 0) {
      doc.setFontSize(9)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(0, 0, 0)
      doc.text('FILTERS APPLIED:', 15, 75)
      
      let filterY = 80
      Object.entries(filters).forEach(([key, value]) => {
        if (value) {
          doc.setFont('helvetica', 'normal')
          doc.setTextColor(100, 100, 100)
          doc.text(`${key.replace(/_/g, ' ').toUpperCase()}: ${value}`, 20, filterY)
          filterY += 5
        }
      })
    }

    // --- Summary Metrics ---
    if (summary && Object.keys(summary).length > 0) {
      doc.setFontSize(10)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(0, 0, 0)
      doc.text('REPORT SUMMARY:', 15, 105)
      
      let summaryX = 15
      Object.entries(summary).forEach(([key, value]) => {
        doc.setFillColor(245, 245, 245)
        doc.roundedRect(summaryX, 110, 40, 15, 2, 2, 'F')
        
        doc.setFontSize(7)
        doc.setFont('helvetica', 'normal')
        doc.setTextColor(100, 100, 100)
        doc.text(key.toUpperCase(), summaryX + 20, 116, { align: 'center' })
        
        doc.setFontSize(10)
        doc.setFont('helvetica', 'bold')
        doc.setTextColor(0, 0, 0)
        doc.text(String(value), summaryX + 20, 122, { align: 'center' })
        
        summaryX += 45
      })
    }

    // --- Data Table ---
    const tableData = data.map(row => 
      columns.map(col => {
        const val = row[col.dataKey]
        if (typeof val === 'object' && val !== null) {
          return val.full_name || val.name || JSON.stringify(val)
        }
        return val ?? '-'
      })
    )

    doc.autoTable({
      startY: summary ? 135 : (filters ? 110 : 80),
      head: [columns.map(c => c.header.toUpperCase())],
      body: tableData,
      theme: 'striped',
      headStyles: {
        fillColor: [0, 0, 0],
        textColor: [255, 255, 255],
        fontSize: 8,
        fontStyle: 'bold',
        halign: 'left'
      },
      styles: {
        fontSize: 8,
        cellPadding: 3,
        overflow: 'linebreak'
      },
      alternateRowStyles: {
        fillColor: [250, 250, 250]
      },
      margin: { top: 15, left: 15, right: 15 },
      didDrawPage: (data: any) => {
        // Footer
        doc.setFontSize(8)
        doc.setTextColor(150, 150, 150)
        const str = `Page ${data.pageNumber} of ${doc.internal.pages.length - 1}`
        doc.text(str, pageWidth / 2, doc.internal.pageSize.height - 10, { align: 'center' })
        doc.text('CONFIDENTIAL DOCUMENT | GENERATED BY ECRAFTZ ERP', 15, doc.internal.pageSize.height - 10)
      }
    })

    doc.save(`${title.replace(/\s+/g, '_')}_${format(new Date(), 'yyyy-MM-dd')}.pdf`)
  }

  /**
   * Generates and downloads a CSV/Excel report
   */
  static exportToCSV(config: ExportConfig) {
    const { title, columns, data } = config
    
    const wsData = data.map(row => {
      const exportRow: Record<string, any> = {}
      columns.forEach(col => {
        const val = row[col.dataKey]
        if (typeof val === 'object' && val !== null) {
          exportRow[col.header] = val.full_name || val.name || JSON.stringify(val)
        } else {
          exportRow[col.header] = val
        }
      })
      return exportRow
    })

    const ws = XLSX.utils.json_to_sheet(wsData)
    const wb = XLSX.utils.book_new()
    XLSX.utils.book_append_sheet(wb, ws, "Report")
    
    XLSX.writeFile(wb, `${title.replace(/\s+/g, '_')}_${format(new Date(), 'yyyy-MM-dd')}.xlsx`)
  }

  /**
   * Generates a detailed audit for a single record
   */
  static async exportSingleRecord(title: string, data: Record<string, any>, organizationName: string) {
    const doc = new jsPDF('p', 'mm', 'a4')
    const pageWidth = doc.internal.pageSize.width
    const timestamp = format(new Date(), 'PPP p')

    // Header
    doc.setFillColor(30, 41, 59) // Slate 800
    doc.rect(0, 0, pageWidth, 50, 'F')
    
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(24)
    doc.setTextColor(255, 255, 255)
    doc.text('ECRAFTZ', 15, 20)
    
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(200, 200, 200)
    doc.text(organizationName.toUpperCase(), 15, 28)
    doc.text(`INDIVIDUAL PERFORMANCE AUDIT | CONFIDENTIAL`, 15, 33)

    // Main Content
    doc.setTextColor(0, 0, 0)
    doc.setFontSize(22)
    doc.setFont('helvetica', 'bold')
    doc.text(title.toUpperCase(), 15, 70)
    
    doc.setDrawColor(200, 200, 200)
    doc.line(15, 75, pageWidth - 15, 75)

    // Data Body
    let y = 90
    doc.setFontSize(12)
    
    Object.entries(data).forEach(([key, value]) => {
      if (y > 270) {
        doc.addPage()
        y = 20
      }

      const label = key.replace(/_/g, ' ').toUpperCase()
      let displayValue = '-'
      
      if (value !== null && value !== undefined) {
        if (typeof value === 'object') {
          displayValue = value.full_name || value.name || JSON.stringify(value)
        } else if (typeof value === 'boolean') {
          displayValue = value ? 'YES' : 'NO'
        } else {
          displayValue = String(value)
        }
      }

      doc.setFont('helvetica', 'bold')
      doc.setFontSize(10)
      doc.setTextColor(100, 100, 100)
      doc.text(label, 15, y)
      
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(11)
      doc.setTextColor(0, 0, 0)
      doc.text(displayValue, 60, y, { maxWidth: pageWidth - 75 })
      
      y += 10
      doc.setDrawColor(240, 240, 240)
      doc.line(15, y - 4, pageWidth - 15, y - 4)
    })

    // Footer
    const pageCount = doc.internal.pages.length - 1
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i)
      doc.setFontSize(8)
      doc.setTextColor(150, 150, 150)
      doc.text(`Authenticated Audit Log | Page ${i} of ${pageCount}`, pageWidth / 2, 285, { align: 'center' })
      doc.text(`Generated on ${timestamp}`, 15, 285)
    }

    doc.save(`Audit_${title.replace(/\s+/g, '_')}_${format(new Date(), 'yyyyMMdd')}.pdf`)
  }
}
